#pragma once

#include "esp_event.h"

#define STACK_SIZE 4096

ESP_EVENT_DECLARE_BASE(EVA_EVENT);

enum {
  EVA_BOOTED,
  EVA_DISPLAY_REFRESH,
  EVA_FRAME_EMIT,
  EVA_LIGHT_UPDATE,
  EVA_SNTP_HEALTHY,
  EVA_SNTP_UNHEALTHY,
  EVA_STATUS_HEALTHY,
  EVA_STATUS_UNHEALTHY,
  EVA_TEMP_UPDATE,
  EVA_TOUCH_TAP,
  EVA_TOUCH_DOUBLETAP,
  EVA_TOUCH_TRIPLETAP,
  EVA_TOUCH_HOLD,
  EVA_WIFI_HEALTHY,
  EVA_WIFI_UNHEALTHY
};
